// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.05 at 12:07:58 PM CEST

package org.opentosca.bus.management.collaboration.model;

import java.util.Objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DiscoveryRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceTemplateFragment" type="{http://collaboration.org/schema}ServiceTemplateFragmentType" maxOccurs="1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiscoveryRequest", propOrder = {"serviceTemplateFragment"})
public class DiscoveryRequest {

    @XmlElement(name = "ServiceTemplateFragment", required = true)
    protected ServiceTemplateFragmentType serviceTemplateFragment;

    public DiscoveryRequest() {}

    public DiscoveryRequest(final ServiceTemplateFragmentType value) {
        this.serviceTemplateFragment = value;
    }

    /**
     * Gets the value of the ServiceTemplateFragment property.
     *
     * @return possible object is {@link ServiceTemplateFragmentType }
     *
     */
    public ServiceTemplateFragmentType getServiceTemplateFragment() {
        return this.serviceTemplateFragment;
    }

    /**
     * Sets the value of the ServiceTemplateFragment property.
     *
     * @param value allowed object is {@link ServiceTemplateFragmentType }
     *
     */
    public void setServiceTemplateFragment(final ServiceTemplateFragmentType value) {
        this.serviceTemplateFragment = value;
    }

    /**
     * Returns a string representation of the DiscoveryRequest
     */
    @Override
    public String toString() {
        if (Objects.nonNull(this.serviceTemplateFragment)) {
            String string = "DiscoveryRequest contains the following NodeTemplates: ";
            for (final NodeTemplate node : this.serviceTemplateFragment.nodeTemplate) {
                string += "NodeTemplate:" + node.templateID + "; " + node.templateType + "; " + node.hostedOn + "; ";
            }
            return string;
        } else {
            return "ServiceTemplateFragment is null";
        }
    }
}
