// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.05 at 12:07:58 PM CEST

package org.opentosca.bus.management.collaboration.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="NodeTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Properties" type="{http://collaboration.org/schema}KeyValueMap"/>
 *       &lt;/sequence>
 *       &lt;attribute name="templateID" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="templateType" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="hostedOn" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeTemplate", propOrder = {"properties"})
public class NodeTemplate {

    @XmlElement(name = "Properties", required = true)
    protected KeyValueMap properties;
    @XmlAttribute(name = "templateID", namespace = "http://collaboration.org/schema", required = true)
    protected QName templateID;
    @XmlAttribute(name = "templateType", namespace = "http://collaboration.org/schema", required = true)
    protected QName templateType;
    @XmlAttribute(name = "hostedOn", namespace = "http://collaboration.org/schema")
    protected QName hostedOn;

    public NodeTemplate() {}

    public NodeTemplate(final KeyValueMap properties, final QName templateID, final QName templateType,
                        final QName hostedOn) {
        this.properties = properties;
        this.templateID = templateID;
        this.templateType = templateType;
        this.hostedOn = hostedOn;
    }

    /**
     * Gets the value of the properties property.
     *
     * @return possible object is {@link KeyValueMap }
     *
     */
    public KeyValueMap getProperties() {
        return this.properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value allowed object is {@link KeyValueMap }
     *
     */
    public void setProperties(final KeyValueMap value) {
        this.properties = value;
    }

    /**
     * Gets the value of the templateID property.
     *
     * @return possible object is {@link QName }
     *
     */
    public QName getTemplateID() {
        return this.templateID;
    }

    /**
     * Sets the value of the templateID property.
     *
     * @param value allowed object is {@link QName }
     *
     */
    public void setTemplateID(final QName value) {
        this.templateID = value;
    }

    /**
     * Gets the value of the templateType property.
     *
     * @return possible object is {@link QName }
     *
     */
    public QName getTemplateType() {
        return this.templateType;
    }

    /**
     * Sets the value of the templateType property.
     *
     * @param value allowed object is {@link QName }
     *
     */
    public void setTemplateType(final QName value) {
        this.templateType = value;
    }

    /**
     * Gets the value of the hostedOn property.
     *
     * @return possible object is {@link QName }
     *
     */
    public QName getHostedOn() {
        return this.hostedOn;
    }

    /**
     * Sets the value of the hostedOn property.
     *
     * @param value allowed object is {@link QName }
     *
     */
    public void setHostedOn(final QName value) {
        this.hostedOn = value;
    }
}
