// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.05 at 12:07:58 PM CEST

package org.opentosca.bus.management.collaboration.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ServiceTemplateFragmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NodeTemplate" type="{http://collaboration.org/schema}NodeTemplate" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceTemplateFragmentType", propOrder = {"nodeTemplate"})
public class ServiceTemplateFragmentType {

    @XmlElement(name = "NodeTemplate", required = true)
    protected List<NodeTemplate> nodeTemplate;

    /**
     * Gets the value of the nodeTemplate property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the nodeTemplate property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getNodeTemplate().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link NodeTemplate }
     *
     *
     */
    public List<NodeTemplate> getNodeTemplate() {
        if (this.nodeTemplate == null) {
            this.nodeTemplate = new ArrayList<>();
        }
        return this.nodeTemplate;
    }
}
